### ISSUE TITLE
What majors does this cover?

### ISSUE THREAD

**Issue by kelseyq** [czchapma/college-diversity-data#1]
I'm guessing from context it's CS, but the README says "STEM"--major breakdowns would be very important if you're trying to do an umbrella STEM chart, and definitions of what should be counted under either STEM or CS need to be included (many schools have both Computer Science and Computer Engineering, for example.)

**Comment by czchapma** [comment]
Great question!  The main vision I have for this project is sharing it with tech companies as a data-driven approach for diversifying their university recruiting pipeline.  So what I'm looking for is a statistic that most-accurately captures that pool.  Naturally, not everyone who goes on to do a tech internship has to major in CS, so it could certainly be broader, but including Biology concentrators might inaccurately reflect the real situation.

What do you think about adding a notes section to clarify what the specific data represents?

**Comment by kelseyq** [comment]
I totally agree that not everyone who enters tech careers needs to have a CS degree, but I also think it's realistic to note that university recruiting pipelines mainly focus on those degrees. If the goal is sharing it with tech companies, I think limiting it to CS degrees makes the most sense--and it'd be hard to accurately compare data if there wasn't at least some attempt at standardization IMO. Folks who were interested in doing broader STEM comparisons could fork the repo or add subfolders.

I do think a notes field would be good to clarify because of the multiple computing major issue--if someone crunched the numbers to combine all CS & closely CS-adjacent numbers, vs taking strictly Bachelor of Science degrees in CS, etc. Excited to contribute what I have!

**Comment by czchapma** [comment]
Awesome, sounds like we're in agreement. I've added a notes section and I'll clarify a bit more of this in an upcoming FAQ!
