### ISSUE TITLE
Add a "middle eastern grouped with white" flag

### ISSUE THREAD

**Issue by sashaperigo** [czchapma/college-diversity-data#10]
Sorry for opening so many issues at once, but another suggestion I have would be to add a flag in the race.csv column header letting users indicate that middle eastern is grouped with white in the data they're including. This would look like the "(\* if grouped with EA)" option in the South Asian header. In the data I just opened a PR for middle eastern students are counted as white, and I think this is fairly common!

**Comment by czchapma** [comment]
Looks like you did that in the Pull Request! Thanks! Am I missing anything?

**Comment by sashaperigo** [comment]
@czchapma haha my apologies! I didn't actually intend to include it in my PR, but I accidentally pushed my changes up so it ended up there anyways. :smile:
