### ISSUE TITLE
How to track multiple majors at different universities?

### ISSUE THREAD

**Issue by sashaperigo** [czchapma/college-diversity-data#8]
Hi! Thank you so much for organizing all of this. While looking over the data just now, one of the things I noticed was that there's currently no clear way to include data from more than one major at a university.

For example, I'm a current student at Stanford. We of course have a Computer Science major, but we also have majors called Symbolic Systems and Computational and Mathematical Sciences that also teach students how to code and graduate a large number of software engineers. I can imagine it might also be useful to include Electrical Engineering in these numbers as well.

If we wanted to include more than one major, how would you like us to do that? My suggestion would be to add a column to the spreadsheet indicating the major the data corresponds to, and allow more than one row per school in the case that data was included for multiple majors.

**Comment by czchapma** [comment]
Great point, I intended to that with the notes section.  That way it could contain any relevant info as opposed to needing a new column for each new exception we brainstorm.  Does that work?

**Comment by sashaperigo** [comment]
@czchapma that sounds great! I just wanted to ask how you wanted us to handle it.
