### ISSUE TITLE
Distinguish between undergraduate and graduate students

### ISSUE THREAD

**Issue by sashaperigo** [czchapma/college-diversity-data#9]
It would be great if we could add a column to the spreadsheet indicating whether or not data was for undergraduate or graduate students (or both I guess, though this doesn't seem ideal). My reasoning is that at some schools diversity numbers differ a lot between the two categories. For example, at Stanford women make up 30% of the undergraduate computer science major, but something like 5-10% of the graduate computer science programs. Let me know what you think!

**Comment by czchapma** [comment]
I also think this could be for the notes, it's almost all undergrad at the moment because grad data isn't available.

**Comment by sashaperigo** [comment]
@czchapma I think that makes sense for now since the grad data is so hard to find, but if you ever do end up getting submissions with graduate data, it might be nice to separate them! If a university has 30% undergrad women, but only 5% grad women, rolling that up into some average like 17% is arguably not telling the whole story.

**Comment by czchapma** [comment]
I completely agree!
